### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by svzosorio** [aurelia/logging-console#6]
Actually the libraries dont have an example of use

**Comment by EisenbergEffect** [comment]
Can you be more specific here?

**Comment by stalniy** [comment]
@EisenbergEffect I believe @svzosorio want to say that each repo doesn't have much documentation (at least examples) of how to use the package. For example, `aurelia-templating` have lots of powerful stuff like managing DOM using `ViewSlot` and `View` and `ViewFactory` but in order to understand all that you  forced to look into code and tests.

And even though that's not enough. It's really a big issue. I was considering to use Aurelia for our new big project but because of lack of docs and existing mobile integration we will proceed with Angular's dirty checking and boilerplate. That's a pity to be honest

**Comment by stalniy** [comment]
just to clarify expected result:

It would be nice to see several examples in README of how library/package can used

**Comment by EisenbergEffect** [comment]
FYI, you need to realize that if you are using Aurelia's APIs a lot, you are using Aurelia incorrectly. You shouldn't need to know most of that. Aurelia favors writing plain JS, not calling Aurelia APIs for things. The exceptions are DI and routing which are mostly documented in our cheat sheet. The fetch client would be another case. It's not released on our docs site, but the readme contains documentation on how to use it.

Yes, I understand we need to have better API docs. But, it's important to realize that Aurelia is fundamentally different from other frameworks. If you are using our APIs directly a lot, you are probably doing it wrong. We need to find a way to communicate this better because I know a lot of developers aren't familiar with this idea and get the wrong impression.

Having said that, more docs are coming. They take time to write though.

I'm closing this since we have docs needs tracked in the documentation repo.

**Comment by stalniy** [comment]
> If you are using our APIs directly a lot, you are probably doing it wrong

@EisenbergEffect I don't think that this statement is correct for developers who want to create libraries based on Aurelia (e.g., mobile framework) or for developers who wants to replace one of the core components of Aurelia (like create a custom logger implementation which sends logs to server or own `BindingLanguage`).

Another example is `if` custom attribute which uses `ViewSlot` and `BoundViewFactory` and `@templateController` which are not documented by the way, however it'd be very handy to know/understand how it works so then that knowledge can be used for creating own custom attributes.

Or child containers... It's not clear how to create and assign child container to subset of DOM/components tree.

And there a lot of such advanced questions which are important for contributors, for people who want to write good quality code with Aurelia, extend it or replace some functionality.

**Comment by EisenbergEffect** [comment]
@stalniy Yes, I agree with you. What I meant is that the typical application developer should not be messing with APIs while developing an app. Absolutely, component and plugin authors are more likely to work with those APIs. We have some new content coming. We are documenting all of that. Mostly it takes time to organize the content, write it and...we also have to build some technology to actually provide the docs in a readable format. So, we are working on all of that to various degrees now. We've got two new articles in the docs as of yesterday. I'll be blogging about that this week. We also have a new update to the "docs" technology itself which will make the TOC of each article more visible and make the docs a more pleasant reading experience. It will introduce "the hub" and be a key shift that will enable us to add other features for the community. We are also looking at how we can get code samples directly inside the API docs themselves and doing some technology experiments there. So, more is coming.

**Comment by adriatic** [comment]
Very good discussion, with even better outcome :-)

**Comment by svzosorio** [comment]
At the time I wrote this had confusion with a part of the api, however looking at google code base and found the way to do it. I am excited using aurelia in my company and look forward to more articles about their use
